# Generated by Django 5.0.6 on 2024-07-08 07:11

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_note_create_date_alter_note_update_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('content', tinymce.models.HTMLField()),
                ('create_date', models.DateField(blank=True)),
                ('update_date', models.DateField(blank=True)),
            ],
        ),
    ]
