# Generated by Django 5.0.6 on 2024-07-08 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='update_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
